name: CI

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'  
  push:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "5.0"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: |
          opam install . --deps-only --with-test
          opam install yojson ounit2

      - run: |
          opam exec -- dune build
          mv _build/default/bin/main.exe _build/default/bin/bioschecker
          ls _build/default/bin/
          
      - run: opam exec -- dune runtest

      - run: ls _build/default/bin/bioschecker

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/default/bin/bioschecker
          asset_name: bioschecker
          tag: latest
          overwrite: true
